# Generated by Django 4.0.1 on 2022-03-15 15:28

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_hotproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='products-images/default.jpg', max_length=500, upload_to=products.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='products-images/default.jpg', max_length=500, upload_to=products.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='products-images/default.jpg', max_length=500, upload_to=products.models.upload_to, verbose_name='Image'),
        ),
    ]
